version: '3'
services:
  app:
    build: .
    ports:
      - 1323:1323
  mysql:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local_database
      # MYSQL_DATABASE: test_db
    ports:
      - 3306:3306
    volumes:
      - ./var/lib/mysql
      # - ./docker_local/db/my.d:/etc/mysql/conf.d/my.d
      - ./docker_local/db/my.cnf:/etc/mysql/conf.d/my.cnf
      
      # - ./initdb.d:/docker-entrypoint-initdb.d
      # - ./initdb.d:/etc/mysql/conf.d